Updated to new naming structure. Added in checks before all pushd commands

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -150,9 +150,6 @@ done
 # Make sure top level directories exist
 mkdir -p $STORE_PATH
 mkdir -p $BACK_UP_PATH
-# and have correct ownership
-# _create_directory_and_set_ownership $STORE_PATH
-# _create_directory_and_set_ownership $BACK_UP_PATH
 
 # Check owner variable is set
 if [ "${GH_OWNER}" == "" ]; then
@@ -163,14 +160,18 @@ if [ "${GH_OWNER}" == "" ]; then
   GH_OWNER=${UC_GH_OWNER}
 fi
 
-# Set sub-component and hostname variables
-if [ "$SUB_COMP" == "" ]; then
-  SUB_COMP=$(_get_sub_component $HOSTNAME)
+# Get the system name, which is everything prior to the first hyphen
+SYSTEM_NAME=$(_get_base_name $HOSTNAME)
+if [ ${SYSTEM_NAME} == "qcr" ]; then
+  printf "${ERROR}The system name cannot be QCR. Please update the machine's hotname or use the hostname argument.\n"
+  exit 1
 fi
-HOSTNAME=$(_get_base_name $HOSTNAME)
+
+# Set the component name
+COMPONENT_NAME=$HOSTNAME
 
 # Set system configuration variables
-GH_REPO="system-configs-$HOSTNAME"
+GH_REPO="system-configs-$SYSTEM_NAME"
 LOCAL_ROOT=$STORE_PATH/$GH_REPO
 GH_PATH=$GH_OWNER/$GH_REPO
 
@@ -186,7 +187,9 @@ fi
 _check_required_variables $GH_PATH
 
 # Print information
-printf "\n${INFO}Hostname: $HOSTNAME\n"
+printf "\n${INFO}System Name: $SYSTEM_NAME\n"
+printf "${INFO}Component Name: $COMPONENT_NAME\n"
+printf "${INFO}Variant: $VARIANT\n"
 printf "${INFO}GitHub Owner: $GH_OWNER\n"
 printf "${INFO}GitHub Branch: $GH_BRANCH\n"
 printf "${INFO}System Configuration Details:\n"
@@ -290,6 +293,10 @@ fi
 
 # Pull down any updates from remote system configuration
 mkdir -p $LOCAL_ROOT
+if [ ! -d ${LOCAL_ROOT} ]; then
+  printf "${ERROR}The directory '${YELLOW}${LOCAL_ROOT}${RESET}' does not exist\n."
+  exit 1
+fi
 pushd $LOCAL_ROOT >/dev/null
 printf "\n${INFO}Pulling from remote system configuration repo...\n"
 git pull
@@ -311,6 +318,10 @@ popd >/dev/null
 # Clone template
 if [ ! -z $TEMPLATE ]; then
   mkdir -p $TEMPLATE_ROOT
+  if [ ! -d ${TEMPLATE_ROOT} ]; then
+    printf "${ERROR}The directory '${YELLOW}${TEMPLATE_ROOT}${RESET}' does not exist\n."
+    exit 1
+  fi
   pushd $TEMPLATE_ROOT >/dev/null
 
   if [ "$(_check_local $TEMPLATE_ROOT)" == "0" ]; then
@@ -382,6 +393,10 @@ if [ ! -z $TEMPLATE ]; then
   fi
 
   # Add and commit local system configuration repo
+  if [ ! -d ${LOCAL_ROOT} ]; then
+    printf "${ERROR}The directory '${YELLOW}${LOCAL_ROOT}${RESET}' does not exist\n."
+    exit 1
+  fi
   pushd $LOCAL_ROOT >/dev/null
   printf "\n${INFO}Adding and committing files...\n"
   git config user.name qcbot
@@ -403,7 +418,11 @@ if [ ! -z $TEMPLATE ]; then
 fi
 
 # Install from local system configuration repo to actual system locations
-INSTALL_ROOT=$LOCAL_ROOT/$SUB_COMP
+INSTALL_ROOT=$LOCAL_ROOT/$COMPONENT_NAME/$VARIANT
+if [ ! -d ${INSTALL_ROOT} ]; then
+  printf "${ERROR}The directory '${YELLOW}${INSTALL_ROOT}${RESET}' does not exist\n."
+  exit 1
+fi
 pushd $INSTALL_ROOT >/dev/null
 
 # files to be installed
@@ -412,7 +431,7 @@ while IFS=  read -r -d $'\0'; do
   CONTENT+=("$REPLY")
 done < <(find . \( -type d \( -exec [ -f {}/.git ] \;  \) -prune \) -o \( -type f -not -path "./install/*" \) -print0)
 
-printf "\n${INFO}Installing Files..."
+printf "\n${INFO}Installing files from '${YELLOW}${INSTALL_ROOT}${RESET}'..."
 for c in "${CONTENT[@]}"; do
   # Get target file, without 
   target="/$(realpath --relative-to="$INSTALL_ROOT" "$c")"
diff --git a/scripts/sync b/scripts/sync
--- a/scripts/sync
+++ b/scripts/sync
@@ -151,24 +151,29 @@ done
 # Make sure top level directories exist
 mkdir -p $STORE_PATH
 mkdir -p $BACK_UP_PATH
-# and have correct ownership
-# _create_directory_and_set_ownership $STORE_PATH
-# _create_directory_and_set_ownership $BACK_UP_PATH
 
 # Check required variables are set
 # Either from command line or user config
 _check_required_variables
 
-# Set repo name
-HOSTNAME=$(_get_base_name $HOSTNAME)
+# Get the system name, which is everything prior to the first hyphen
+SYSTEM_NAME=$(_get_base_name $HOSTNAME)
+if [ ${SYSTEM_NAME} == "qcr" ]; then
+  printf "${ERROR}The system name cannot be QCR. Please update the machine's hotname or use the hostname argument.\n"
+  exit 1
+fi
+
+
+# Set the repo name, based on the system name
+# and if this is a template or not
 if [ -z $TEMPLATE ]; then
-  GH_REPO="system-configs-$HOSTNAME"
+  GH_REPO="system-configs-$SYSTEM_NAME"
 else
   GH_REPO="template-$TEMPLATE"
 fi
 
 
-# Set github path and local repo root path (root)
+# Set github path and local repo root path 
 GH_PATH="$GH_OWNER/$GH_REPO"
 LOCAL_ROOT=$STORE_PATH/$GH_REPO
 
@@ -176,7 +181,7 @@ LOCAL_ROOT=$STORE_PATH/$GH_REPO
 mkdir -p $LOCAL_ROOT
 
 # Print information to user
-printf "\n${INFO}Hostname: $HOSTNAME\n"
+printf "\n${INFO}System Name: $SYSTEM_NAME\n"
 printf "${INFO}GitHub Email: $GH_EMAIL\n"
 printf "${INFO}GitHub Owner: $GH_OWNER\n"
 printf "${INFO}GitHub Repo: $GH_REPO\n"
@@ -212,10 +217,11 @@ fi
 
 # Pull down latest
 if [ "$PULL" == "1" ]; then
-    # TODO: Deal with local changes, merge conflicts, etc.
+
+    # ToDo check for merge conflicts
+
     printf "\n${INFO}Pulling from remote...\n"
     git pull
-    # TODO: pulling down new files doesn't install them
 fi
 
 
@@ -223,7 +229,7 @@ fi
 if [ ! -z $TEMPLATE ]; then
 
   # Get configuration files
-  CONFIG_ROOT=$STORE_PATH/"system-configs-$HOSTNAME"
+  CONFIG_ROOT=$STORE_PATH/"system-configs-$SYSTEM_NAME"
   FILES=$(find ${CONFIG_ROOT} -type f -not -path "*.git*" -not -name "README.md")
 
   # Add any missing files to template
@@ -258,6 +264,10 @@ fi
 
 # Navigate to local repo, set user email
 # GitHub uses user email to show committer not GitHub username
+if [ ! -d "${LOCAL_ROOT}" ]; then
+  printf "${ERROR}The directory '${YELLOW}${LOCAL_ROOT}${RESET}' does not exist.\n"
+  exit 1
+fi
 pushd $LOCAL_ROOT >/dev/null
 git config user.email $GH_EMAIL
 
diff --git a/scripts/track b/scripts/track
--- a/scripts/track
+++ b/scripts/track
@@ -202,22 +202,28 @@ done
 # Make sure top level directories exist
 mkdir -p $STORE_PATH
 mkdir -p $BACK_UP_PATH
-# and have correct ownership
-# _create_directory_and_set_ownership $STORE_PATH
-# _create_directory_and_set_ownership $BACK_UP_PATH
 
 
-# Get sub-component, which according to OUT001 (Naming Conventions), is everything after the first hyphen
-if [ "$SUB_COMP" == "" ]; then
-  SUB_COMP=$(_get_sub_component $HOSTNAME)
+# # Get sub-component, which is everything after the first hyphen
+# if [ "$SUB_COMP" == "" ]; then
+#   SUB_COMP=$(_get_sub_component $HOSTNAME)
+# fi
+
+# Get the system name, which is everything prior to the first hyphen
+SYSTEM_NAME=$(_get_base_name $HOSTNAME)
+if [ ${SYSTEM_NAME} == "qcr" ]; then
+  printf "${ERROR}The system name cannot be QCR. Please update the machine's hotname or use the hostname argument.\n"
+  exit 1
 fi
 
-# Set repo name, based on the hostname, which according to OUT001 (Naming Conventions), is everything prior to the first hyphen
-HOSTNAME=$(_get_base_name $HOSTNAME)
-GH_REPO="system-configs-$HOSTNAME"
+# Set the repo name, which is based on the SYSTEM_NAME
+GH_REPO="system-configs-$SYSTEM_NAME"
+
+# Get the component name
+COMPONENT_NAME=$HOSTNAME
 
 # Create source path where files are to be stored and symlinked from
-SRC_PATH=$STORE_PATH/$GH_REPO/$SUB_COMP/
+SRC_PATH=$STORE_PATH/$GH_REPO/$COMPONENT_NAME/$VARIANT
 mkdir -p $SRC_PATH
 
 # Error checking, need at least one file
@@ -227,8 +233,9 @@ if [ ${#TARGET_FILES[@]} -eq 0 ]; then
 fi
 
 # Print info
-printf "\n${INFO}Hostname: ${HOSTNAME}\n"
-printf "${INFO}Sub-Component: $SUB_COMP\n"
+printf "\n${INFO}System Name: $SYSTEM_NAME\n"
+printf "${INFO}Component Name: $COMPONENT_NAME\n"
+printf "${INFO}Variant: $VARIANT\n"
 printf "${INFO}Source Path: $SRC_PATH\n"
 
 # Display heading
